# Generated by Django 3.2.4 on 2021-06-21 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('created', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('link', models.CharField(default='', max_length=50, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=50, verbose_name='Статус')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ядро пользователя')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='Текст сообщения')),
                ('msg_hash', models.CharField(default='', max_length=100, verbose_name='Хэш сообщения')),
                ('sent', models.DateTimeField(auto_now=True, verbose_name='Время и дата отправки')),
                ('is_read', models.BooleanField(default=False, verbose_name='')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dialog', verbose_name='Диалог')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Беседа',
                'verbose_name_plural': 'Беседы',
            },
        ),
        migrations.AddField(
            model_name='dialog',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to='main.profile', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to='main.profile', verbose_name='Отправитель'),
        ),
    ]
